query_name: stamps
query_sigs: /home/ntpierce/2022-stamps-magsearch/siglist.txt
wort_sigs: /group/ctbrowngrp/irber/data/wort-data/wort-sra/sigs
s3_dir: outputs/wort-sra/sigs
threshold: 0.01
ksize: 31
out_dir: "output.magsearch.k31"
