name: magsearch-2022
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - snakemake=7.8.0
  - sourmash>=4.4.0
  - pandas>=1.4.2
  - seaborn=0.11.0
  - jupyterlab
  - tqdm
  - screed
